---
- name: Create public subnets
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "{{ item.name }}"
  loop:
    - { name: public-subnet-1, cidr: 10.0.1.0/24, az: "{{ region }}a" }
    - { name: public-subnet-2, cidr: 10.0.2.0/24, az: "{{ region }}b" }
  register: public_subnets

- name: Create private subnets
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "{{ item.name }}"
  loop:
    - { name: private-subnet-1, cidr: 10.0.3.0/24, az: "{{ region }}a" }
    - { name: private-subnet-2, cidr: 10.0.4.0/24, az: "{{ region }}b" }
  register: private_subnets

- set_fact:
    public_subnet_ids: "{{ public_subnets.results | map(attribute='subnet.id') | list }}"
    private_subnet_ids: "{{ private_subnets.results | map(attribute='subnet.id') | list }}"