---
- name: Allocate Elastic IP for NAT Gateway
  amazon.aws.ec2_eip:
    region: "{{ region }}"
    state: present
    in_vpc: true
  register: nat_eip

- name: Create NAT Gateway
  amazon.aws.ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ public_subnet_ids[0] }}"
    allocation_id: "{{ nat_eip.allocation_id }}"
    region: "{{ region }}"
    wait: yes
  register: nat_gateway

- set_fact:
    nat_gateway_id: "{{ nat_gateway.nat_gateway_id }}"