---
- name: Create S3 Gateway Endpoint
  amazon.aws.ec2_vpc_endpoint:
    vpc_id: "{{ vpc_id }}"
    service: s3
    state: present
    route_table_ids: "{{ private_route_table_ids }}"
    region: "{{ region }}"
    policy_file: "{{ role_path }}/files/s3_endpoint_policy.json"

- name: Create DynamoDB Gateway Endpoint
  amazon.aws.ec2_vpc_endpoint:
    vpc_id: "{{ vpc_id }}"
    service: dynamodb
    state: present
    route_table_ids: "{{ private_route_table_ids }}"
    region: "{{ region }}"
    policy_file: "{{ role_path }}/files/dynamodb_endpoint_policy.json"