---
- hosts: localhost
  gather_facts: false
  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  roles:
    - vpc
    - subnet
    - route_table
    - nat_gateway
    - internet_gateway
    - gateway_endpoint